#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
# first run tests
# php artisan test --parallel

# ensure it builds
# npm run build

# fix the lint issues
composer lint:fix
npm run lint:fix

# add the fixed files
git add -u
